### ISSUE TITLE
unknown inside temperature. doing nothing.

### ISSUE THREAD

**Issue by kaczkalolo** [wogri/hass-blinds#1]
I've set up all the blinds and in the input_text helper i get: unknown inside temperature. doing nothing.
As an inside for each blind i've put:  inside_temperature: sensor.inside_temperature in apps.yaml
That's my inside termometer. I dont have thermostats at all- well i do have one but it is only for heating which is off in summer time.
What am i doing not right?

**Comment by wogri** [comment]
Hi and thanks for using this :) 

What happens if you go to your home assistant and put that sensor into the developer tools / states section? 
In my case it looks like this: 

![Screenshot 2021-07-27 at 11 39 55](https://user-images.githubusercontent.com/4959854/127132734-739b8cbe-e507-4237-80d9-ec6ea994932c.png)

**Comment by kaczkalolo** [comment]
![image](https://user-images.githubusercontent.com/47222608/127132974-eab8a3fe-777a-4936-b2ad-90ee79b59ea6.png)

27C inside- it's very hot today :0

**Comment by wogri** [comment]
It's too hot, you clearly need some blind automation :) 

It's clear that the sensor works. The problem is though that it doesn't have a `current_temperature` attribute. In that case, just add `inside_temperature_is_no_thermostat: true` to your config like in the screenshot below. 

![Screenshot 2021-07-27 at 11 46 37](https://user-images.githubusercontent.com/4959854/127133697-b84bc1b7-5d32-471d-98ed-f99a9159a8f0.png)

**Comment by kaczkalolo** [comment]
Ok now i got: Blinds are controlled manually- so how do i release them from being controlled manually? tried to restart appdeamon but that did not help. 
Tried with touch blinds.py but nothing happens

**Comment by wogri** [comment]
Blinds are controlled manually is a state where the engine feels: "that's what you configured, I'm doing what you requested". 
Now I need to see your apps.yml.

**Comment by kaczkalolo** [comment]
`apps $ cat apps.yaml`

```yaml
global_modules:
- blinds_lib
  - hysteresis_lib
- sun_lib
- hysteresis_lib

sun:
  class: Sun
  module: sun
  global_dependencies:
  - sun_lib
  brightness_sensor: sensor.illumination_158d00068a014f
  brightness_at_dawn_sensor: sensor.illumination_158d00068a014f

max_temp:
  class: MaxTemp
  module: max_temp
  outside_temp_sensor: sensor.outside_temperature
  max_temp_sensor: input_number.max_outside_temp_over_24_hours
  max_temp_sensor_yesterday: input_number.yesterdays_max_outside_temp_over_24_hours

blind_livingroom1:
  class: Blinds
  module: blinds
  global_dependencies:
  - blinds_lib
  - hysteresis_lib
  - sun_lib
  blind: cover.living_room_blind_1
  inside_temperature: sensor.inside_temperature
  inside_temperature_is_no_thermostat: true
  max_temp_sensor_value_yesterday: input_number.yesterdays_max_outside_temp_over_24_hours
  wind_alarm: binary_sensor.wind_alarm
  outside_temperature_sensor: sensor.outside_temperature
  blind_config:
    azimuth_entry: 105
    azimuth_exit: 250
    manual_day_control: True
    manual_night_control: True
    max_inside_temperature_cold_day: 24
    kill_switch_hold_time: 1

blind_livingroom2:
  class: Blinds
  module: blinds
  global_dependencies:
  - blinds_lib
  - hysteresis_lib
  - sun_lib
  blind: cover.living_room_blind_2
  inside_temperature: sensor.inside_temperature
  inside_temperature_is_no_thermostat: true
  max_temp_sensor_value_yesterday: input_number.yesterdays_max_outside_temp_over_24_hours
  wind_alarm: binary_sensor.wind_alarm
  outside_temperature_sensor: sensor.outside_temperature
  blind_config:
    azimuth_entry: 105
    azimuth_exit: 250
    manual_day_control: True
    manual_night_control: True
    max_inside_temperature_cold_day: 24
    kill_switch_hold_time: 1

blind_diningroom3:
  class: Blinds
  module: blinds
  global_dependencies:
  - blinds_lib
  - hysteresis_lib
  - sun_lib
  blind: cover.dining_room_blind_3
  inside_temperature: sensor.inside_temperature
  inside_temperature_is_no_thermostat: true
  max_temp_sensor_value_yesterday: input_number.yesterdays_max_outside_temp_over_24_hours
  wind_alarm: binary_sensor.wind_alarm
  outside_temperature_sensor: sensor.outside_temperature
  blind_config:
    azimuth_entry: 180
    azimuth_exit: 290
    manual_day_control: True
    manual_night_control: True
    max_inside_temperature_cold_day: 24
    kill_switch_hold_time: 1

blind_diningroom4:
  class: Blinds
  module: blinds
  global_dependencies:
  - blinds_lib
  - hysteresis_lib
  - sun_lib
  blind: cover.dining_room_blind_4
  inside_temperature: sensor.inside_temperature
  inside_temperature_is_no_thermostat: true
  max_temp_sensor_value_yesterday: input_number.yesterdays_max_outside_temp_over_24_hours
  wind_alarm: binary_sensor.wind_alarm
  outside_temperature_sensor: sensor.outside_temperature
  blind_config:
    azimuth_entry: 180
    azimuth_exit: 290
    manual_day_control: True
    manual_night_control: True
    max_inside_temperature_cold_day: 24
    kill_switch_hold_time: 1

blind_kitchen:
  class: Blinds
  module: blinds
  global_dependencies:
  - blinds_lib
  - hysteresis_lib
  - sun_lib
  blind: cover.kitchen_blind_1
  inside_temperature: sensor.inside_temperature
  inside_temperature_is_no_thermostat: true
  max_temp_sensor_value_yesterday: input_number.yesterdays_max_outside_temp_over_24_hours
  wind_alarm: binary_sensor.wind_alarm
  outside_temperature_sensor: sensor.outside_temperature
  blind_config:
    azimuth_entry: 180
    azimuth_exit: 290
    manual_day_control: True
    manual_night_control: True
    max_inside_temperature_cold_day: 24
    kill_switch_hold_time: 1
```

**Comment by wogri** [comment]
Yeah, `manual_day_control: True` and `manual_night_control: True` mean: don't pull the blinds down or up automatically. Remove those lines and see what it does (also: I don't know what you would expect, I'd be curious to know).

**Comment by kaczkalolo** [comment]
Ok now it has started to do something:
- living room lbinds got open: Blinds go up, there is not enough sun
- dining room- Sun has not reached the blind yet
- kitchen - Sun has not reached the blind yet
And after some time all changed to Kill switch is ON but i have not done anything...

What i want is to automate it at day time and i will close them at night and they should open in the morning automatically.
What i would also want is to close them automatically but not totally but to 15% then i still get some light through the holes. 

Oh one more thing- i don't have a lux sensor outside so i used one that i have inside- now it is sunny and this is what i have:
![image](https://user-images.githubusercontent.com/47222608/127143531-d34913ee-83d8-4e75-92c1-dd2c34e0b58f.png)

**Comment by wogri** [comment]
Kill switch is turned on if the expected state (for example blinds position = 100) does not match reality. That means the system thinks that a human overrode what the computer decided, and it will not do anything for the default of 4 hours. 
That could also be because it set an angle for your blinds but your system doesn't support this. Look at the logs of appdaemon, it will spit out useful information about the kill switch (why it turned it on). 

> What i would also want is to close them automatically but not totally but to 15% then i still get some light through the holes

I do this with the angle that I can set with my blinds. If your blinds don't support an angle you will have to do some trickery in the code to leave them 15% open (e. g. modify the DOWN variable in lib/blinds.py). 
The code actually adjusts the angle depending on the height of the sun so you always get maximum light in. 

The lux sensor sensor inside will give you very different values than an outside one (e. g. I put the blinds down at 60,000 lux outside for example, you will never reach this inside), you would have to adjust sun.py probably, otherwise it would not detect direct sunlight or situations where it would make sense that the blinds are down during the day.

**Comment by kaczkalolo** [comment]
2021-07-27 12:35:06.089131 INFO blind_diningroom4: Turning Kill switch on: last_postion: 100, knx_current_position: 100, last_angle: 100, knx_current_angle: None
2021-07-27 12:35:06.100784 INFO blind_kitchen: Turning Kill switch on: last_postion: 100, knx_current_position: 100, last_angle: 100, knx_current_angle: None
2021-07-27 12:35:06.104525 INFO blind_diningroom3: Turning Kill switch on: last_postion: 100, knx_current_position: 100, last_angle: 100, knx_current_angle: None
2021-07-27 12:35:06.112659 INFO blind_livingroom1: Turning Kill switch on: last_postion: 100, knx_current_position: 100, last_angle: 100, knx_current_angle: None
2021-07-27 12:35:06.119744 INFO blind_livingroom2: Turning Kill switch on: last_postion: 100, knx_current_position: 100, last_angle: 100, knx_current_angle: None

Yeah i have simple blinds without tilt. How can i disable that?
I need to think about some light sensor then- anything cheap You would recommend?

**Comment by wogri** [comment]
okay, that explains the kill switch. there is no option to disable angle checking. But I will write something for you, it's not hard. It might take me a day or three, ping me by the end of the week if I didn't come back to you. 

As for light sensor: I can't give you a good advice, my light sensor also includes a rain and wind sensor and is more than 800 Euros, so I won't recommend that one :)

**Comment by kaczkalolo** [comment]
Cool.
Thanks a lot. I really appreciate your work. 
Great stuff 👍

**Comment by joelinux60** [comment]
> Oh one more thing- i don't have a lux sensor outside so i used one that i have inside- now it is sunny and this is what i have:
> ![image](https://user-images.githubusercontent.com/47222608/127143531-d34913ee-83d8-4e75-92c1-dd2c34e0b58f.png)

Hello,
happened to be in similar situation. Could resolve the unknown inside temperature issue thanks to information found here. Now I'm seeing Kill switch being turned on due to my covers are 'simple' ones not allowing for a angle/Tilt setting. Going to keep an eye here to give an enhanced version a try.

Regarding lux sensor. A Xiaomi MiJia GZCGQ01LM is working here. It's installed inside, behind window and delivers sensor data up to 80'000 lux for a clear and sunny day. Need to take care to not close blind too much of that window where my  GZCGQ01LM is looking through.  

![image](https://user-images.githubusercontent.com/47098324/127267798-489683e5-571f-4342-abeb-bd0d0025cdfe.png)

Please see chart below for yesterday's lux measurements

![image](https://user-images.githubusercontent.com/47098324/127268514-bcfe0303-97eb-4535-a021-7ebc748929a1.png)

Kind regards

**Comment by kaczkalolo** [comment]
I've ordered that sensor yesterday- will get it today.
I'm wondering what would be the best place to mount it??? Does it need to be direct sunlight or can it be mounted under roofs ledge? And which side of house would be the best?

**Comment by wogri** [comment]
https://github.com/wogri/hass-blinds/commit/d9ecae4986634080b7bf58da9bb5adcde8ea65b4 (which I also merged into master) should do the needful. After applying this patch setting `disable_tilt: true` in your yaml blind config should solve the problem with the kill switch. I only tested it in a unit test, so let me know if it works for real.

**Comment by wogri** [comment]
> I'm wondering what would be the best place to mount it??? Does it need to be direct sunlight or can it be mounted under roofs ledge? And which side of house would be the best?

Top of your house so it can get direct sunlight. if it's under the roofs ledge it will not give you accurate numbers.

**Comment by joelinux60** [comment]
Hi,

did download from master and installed all of it to appdaemon. Adding `disable_tilt: true` yields into:

```
2021-07-28 14:46:18.755207 WARNING blind_HWR: ------------------------------------------------------------
2021-07-28 14:46:18.754865 WARNING blind_HWR: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/appdaemon/app_management.py", line 161, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/utils.py", line 299, in run_in_executor
    response = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/conf/apps/blinds.py", line 15, in initialize
    self.tick(None)
  File "/conf/apps/blinds.py", line 179, in tick
    self.evaluate()
  File "/conf/apps/blinds.py", line 76, in evaluate
    we_have_work = self.b.Evaluate()
  File "/conf/apps/lib/blinds_lib.py", line 280, in Evaluate
    angle_diff = abs(self.last_angle - self.knx_current_angle)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

2021-07-28 14:46:18.754003 WARNING blind_HWR: ------------------------------------------------------------
2021-07-28 14:46:18.753653 WARNING blind_HWR: Worker Ags: {}
2021-07-28 14:46:18.753284 WARNING blind_HWR: Unexpected error in worker for App blind_HWR:
2021-07-28 14:46:18.752773 WARNING blind_HWR: ------------------------------------------------------------
```

My apps.yml looks like this:

```
hello_world:
  module: hello
  class: HelloWorld

global_modules:
 - blinds_lib
 - hysteresis_lib
 - sun_lib
 - hysteresis_lib

sun:
  class: Sun
  module: sun
  global_dependencies: 
  - sun_lib
  brightness_sensor: sensor.gzcgq01lm_xiaomi_mijia_light_intensity_sensor_illuminance_lux
  brightness_at_dawn_sensor: sensor.gzcgq01lm_xiaomi_mijia_light_intensity_sensor_illuminance_lux

max_temp:
  class: MaxTemp
  module: max_temp
  outside_temp_sensor: sensor.ble_temperature_eingang_sensor
  max_temp_sensor: input_number.max_outside_temp_over_24_hours
  max_temp_sensor_yesterday: input_number.yesterdays_max_outside_temp_over_24_hours

blind_HWR:
  class: Blinds
  module: blinds
  global_dependencies: 
  - blinds_lib
  - hysteresis_lib
  - sun_lib
  blind: cover.rolllade_hwr
  contact: binary_sensor.hwr_xiaomi_door_window_contact_contact
  inside_temperature: sensor.xiaomi_temphumhpa_hwr_temperature
  inside_temperature_is_no_thermostat: true
  max_temp_sensor_value_yesterday: input_number.yesterdays_max_outside_temp_over_24_hours
  wind_alarm: binary_sensor.devolo_arbeit_tamper
  outside_temperature_sensor: sensor.ble_temperature_eingang_sensor
  blind_config:
    azimuth_entry: 180
    azimuth_exit: 260
    window_type: door
    kill_switch_hold_time: 1
    disable_tilt: true
```

**Comment by wogri** [comment]
ah yes, please try the latest master, I just [fixed this](https://github.com/wogri/hass-blinds/commit/5dd27f9285770246061ab834a2ef6eb786c4b57b). I won't have time to write a unit test to catch this today, though...

**Comment by joelinux60** [comment]
Much better now. Thank you!

It's cloudy weather today, so will see if shading takes action. 

```
2021-07-28 15:35:19.047997 INFO blind_HWR: Minimum temperature to get down blinds is: 21.0C (seems like warm season)
2021-07-28 15:35:19.033475 INFO blind_HWR: Not setting the tilt as these blinds don't have that feature.
2021-07-28 15:35:18.962643 INFO blind_HWR: Changing position of blind cover.rolllade_hwr from 90 to 100 because: Blinds go up, there is not enough sun
2021-07-28 15:35:18.943821 INFO blind_HWR: Initializing blinds...
2021-07-28 15:35:18.928867 INFO AppDaemon: Initializing app blind_HWR using class Blinds from module blinds
2021-07-28 15:35:18.926271 INFO AppDaemon: Terminating blind_HWR
2021-07-28 15:35:18.907479 INFO AppDaemon: Found 4 total apps
2021-07-28 15:35:18.903397 INFO AppDaemon: App 'blind_HWR' changed
2021-07-28 15:35:18.894895 INFO AppDaemon: /conf/apps/apps.yaml added or modified
2021-07-28 15:35:18.867459 INFO AppDaemon: Reading config
2021-07-28 15:34:28.917910 INFO blind_HWR: Minimum temperature to get down blinds is: 21.0C (seems like warm season)
2021-07-28 15:34:28.893422 INFO blind_HWR: Initializing blinds...
2021-07-28 15:34:28.886521 INFO AppDaemon: Initializing app blind_HWR using class Blinds from module blinds
2021-07-28 15:34:28.871964 INFO AppDaemon: Reloading Module: /conf/apps/lib/blinds_lib.py
2021-07-28 15:34:28.864973 INFO AppDaemon: Terminating blind_HWR

```

**Comment by kaczkalolo** [comment]
Ok I got the luminance Sensor and it works great now.!!! Love it. Thanks so much for your work. 
I got one more question- LUX DARK and LUX DARK WITH LIGHT INSIDE- First one when Light is below blinds will close right? The second one- what is it for? And how do you measure it? Some other Sensor inside?

**Comment by wogri** [comment]
Good question. LUX DARK is correct - if the lux value is below this value then the blinds will close. The second one is only relevant if you have defined `dawn_lights` like [here](https://github.com/wogri/hass-blinds/blob/7327b717d40969714143947df1a665ef208f67b3/apps.yaml#L151): 

```yaml
blind_esszimmer_west_hebe_schiebetuer:
  class: Blinds
  module: blinds
  global_dependencies: 
  - blinds_lib
  - hysteresis_lib
  - sun_lib
  inside_temperature: sensor.erdgeschoss_esszimmer_temperatur
  inside_temperature_is_no_thermostat: true
  max_temp_sensor_value_yesterday: input_number.yesterdays_max_outside_temp_over_24_hours
  blind: cover.raffstore_erdgeschoss_kueche_schiebetuer_west
  wind_alarm: binary_sensor.wetter_zentrale_funktionen_windalarm_jalousien
  outside_temperature_sensor: sensor.wetter_zentrale_funktionen_aussentemperatur
  contact: binary_sensor.kontakt_erdgeschoss_kueche_hebe_schiebetuer
  blind_config:
    azimuth_entry: 173
    azimuth_exit: 276
    ledge: 200
    window_azimuth_position: 263
    window_type: door
    kill_switch_hold_time: 4
    # manual_night_control: True
  dawn_lights:
  - light.dimmer_erdgeschoss_essbereich
  - light.dimmer_erdgeschoss_kuechenzeile
  - light.licht_erdgeschoss_esstisch
 ```

Once you set dawn_lights and _one of those lights is turned on_ then the threshold to put the blinds down will be raised to `LUX_DARK_WITH_LIGHT_INSIDE`. The reason for this is that my wife complained why the blinds haven't gone down yet when she turned on the light because she felt "in the spotlight". I realized that one needs a different threshold (higher lux value) for when the lights are turned on for certain rooms (like our dining room) because the subjective feeling for how dark it is outside changes once the lights are on.
