### ISSUE TITLE
Blind is closing even though door is open

### ISSUE THREAD

**Issue by kaczkalolo** [wogri/hass-blinds#4]
I have got this blind that is closing even though it has contact parameter set like below:

```yaml
blind_diningroom1:
  class: Blinds
  module: blinds
  global_dependencies:
  - blinds_lib
  - hysteresis_lib
  - sun_lib
  blind: cover.dining_room_blind_1
  inside_temperature: sensor.inside_temperature
  inside_temperature_is_no_thermostat: true
  max_temp_sensor_value_yesterday: input_number.yesterdays_max_outside_temp_over_24_hours
  wind_alarm: binary_sensor.wind_alarm
  outside_temperature_sensor: sensor.outside_temperature
  contact: binary_sensor.door_window_sensor_158d0004798c85
  blind_config:
    azimuth_entry: 361
    azimuth_exit: 362
    max_inside_temperature_cold_day: 24
    kill_switch_hold_time: 2
    disable_tilt: true
```
 
Entity
binary_sensor.door_window_sensor_158d0004798c85
State on
State attributes (YAML, optional)
Open since: '300'
voltage: 2.98
battery_level: 37
friendly_name: Patio Door Sensor
device_class: door

Last changed:
August 4, 2021, 6:56:42 PM
Last updated:
August 4, 2021, 7:01:41 PM

And piece of log when it was closed:
2021-08-04 20:42:45.451118 INFO blind_diningroom1: Changing position of blind cover.dining_room_blind_1 from 100 to 20 because: Down because of darkness

And history of that binary sensor:
![image](https://user-images.githubusercontent.com/47222608/128240671-9b428c3f-6280-419b-b40a-a7dbeba3d895.png)
