### ISSUE TITLE
Feature request: Do not round blind position to multiple of tens

### ISSUE THREAD

**Issue by kaczkalolo** [wogri/hass-blinds#5]
Hi,
Please add possibility to position blinds to 1% of precision in class Blind.
`class Blind:`
`  """Entscheidet über die Rolladen-Situation"""`

`  UP = 100`
`  DOWN = 20`

Now I can't assign for example value 15 for DOWN variable and i my case 15 is the best. 10 is too much and 20 is not enough.

Thanks

**Comment by wogri** [comment]
Please try the latest version, I implemented [this patch](https://github.com/wogri/hass-blinds/commit/82dc18c9796aabccb6d46e50f91f09de1431c8e4) - you will have to set `ignore_10_percent_precision: true` in your apps.yaml per blind. Try with one blind first, because I'm not sure if I missed something and if it will actually work. 

Example config: 

```yaml
blind_gang_og_sued:
  class: Blinds
  module: blinds
  global_dependencies: 
  - blinds_lib
  - hysteresis_lib
  - sun_lib
  blind: cover.raffstore_obergeschoss_gang_drehtuer_sued                            
  contact: binary_sensor.kontakt_obergeschoss_ausgang_terasse
  inside_temperature: climate.thermostat_obergeschoss_kinderzimmer_emma             
  wind_alarm: binary_sensor.wetter_zentrale_funktionen_windalarm_jalousien          
  outside_temperature_sensor: sensor.wetter_zentrale_funktionen_aussentemperatur
  max_temp_sensor_value_yesterday: input_number.yesterdays_max_outside_temp_over_24_hours
  ignore_10_percent_precision: true
  blind_config:
    window_height: 205
    ledge: 135
    azimuth_entry: 89
    window_azimuth_position: 173
    window_type: door
    azimuth_exit: 210
    manual_night_control: True
    kill_switch_hold_time: 2

```
